on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jonaseberle/github-action-setup-ddev@v1
      - uses: matt-ball/newman-action@master
        with:
          collection: test/postman/news.postman_collection.json
          insecure: true
          apiKey:
          environment:
